main: me.Dzyre.lessEssentials.Main
name: lessEssentials
version: 0.1
api-version: 1.19

commands:
  tpa:
    usage: /<command>
  tpaccept:
    usage: /<command>
  sethome:
    usage: /<command>
  delhome: 
    usage: /<command>
  home:
    usage: /<command>
  homes:
    usage: /<command>
  spawn:
    usage: /<command>
  warp:
    usage: /<command>
  setwarp:
    usage: /<command>
  delwarp: 
    usage: /<command>